
description: |
  This is your journey, where all the narative is stored e.g. the plot.
  Every scenario must belong to a universe in which it can take place.
  Therefore it gets access to all places and NPC's made available by
  that universe and it must apply to the rules defined.
  When you start a new campagin, you would usually begin with choosing
  you universe and then select one of the available scenarios for that 
  particular universe. You can add more scenarios to that campagin
  later as long as they belong to the same universe.

