
type: collection

description: |
  Whenever you are joining a new campaign you must first choose
  a universe in which you are going to play. This is where you define the 
  rules, places or even NPC's you may encounter during your journey.

get:
  is: [ searchable, restrictable ]


/{id}:
  type: member
